spring:
  application:
    name: mall-job
  datasource:
    url: jdbc:mysql://localhost:3306/spa_mall?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456
  mail:
    protocol: smtp
    host: smtp.163.com
    port: 25
    username: wzyhddy@163.com
    password: XUbFj6whdUDPj3gc
    default-encoding: UTF-8
  rabbitmq:
    host: 124.221.142.75
    port: 5672
    username: rabbitmq
    password: rabbitmq
  redis:
    database: 5
    host: 124.221.142.75
    port: 6379
    password: cool
    timeout: 5000
  elasticsearch:
    host: 124.221.142.75
    port: 9200
    username: elastic
    password: Elastic_STtwmz
server:
  port: 8012

logging:
  level:
    com:
      net:
        sparrow:
          mapper: debug
oss:
  qiniu:
    accessKey: V-Tz0xdLnWFHbHM9mmd78exWVcqAWQeoxrzwSH8i
    secretKey: YR39wsPfMxOTedNizE8xcJj6J4rzSphPHzQhXs2i
    bucketPictureName: spa-mall
    domainPicture: http://ss2t6snkb.hd-bkt.clouddn.com/
    bucketFileName: spa-mall
    domainFile: http://ss2t6snkb.hd-bkt.clouddn.com/