spring:
  application:
    name: mall-job
  datasource:
    url: jdbc:mysql://localhost:3306/spa_mall?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456
  mail:
    protocol: smtp
    host: smtp.163.com
    port: 25
    username: wzyhddy@163.com
    password: XUbFj6whdUDPj3gc
    default-encoding: UTF-8
  freemarker:
    cache: false
    settings:
      classic_compatible: true
    suffix: .html
    charset: UTF-8
    template-loader-path: classpath:/templates/
server:
  port: 8012

logging:
  level:
    com:
      net:
        sparrow:
          mapper: debug